spring:
  application:
    name: jimmer-playground
  threads:
    virtual:
          enabled: true
  flyway:
    enabled: true
    encoding: UTF-8
    baseline-version: 3000
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb?useUnicode=true&characterEncoding=utf8
jimmer:
  language: kotlin
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
